import { v4 as uuid } from 'uuid';
import {
  //FICTION
  HarryPotterAndTheCursedChild,
  MansSearchForMeaning,
  TheArcher,
  TheGreatTrainJourney,
  TheKiteRunner,
  ThreeThousandStitches,
  TheLittlePrince,
  HomeBody,
  WarAndPeace,
  LandourBazaar,
  LoveSonnetsOfGhalib,
  Siddhartha,
  //NON-FICTION
  MyJourney,
  ShoeDog,
  WhyIAmAnAtheist,
  Rajneeti,
  TheDhoniTouch,
  DiaryOfAYoungGirl,
  IndiasStruggleForIndependence,
  Karma,
  SevenSecretsOfShiva,
  RumisLittleBookOfLife,
  MyGita,
  Death,
  //SELF-HELP
  Ikigai,
  LifesAmazingSecrets,
  StarWithWhy,
  ThePowerOfYourSubconsiousMind,
  ThePsycologyOfMoney,
  ThinkAndGrowRich,
  ThinkLikeAMonk,
  BeleiveInYourself,
  AtomicHabits,
  Mindset,
  ChanakyaInDailyLife,
  Attached,
} from '../../assets';

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

const calculateDiscountedAmount = (originalPrice, currentPrice) =>
  originalPrice - currentPrice;

const calculateDiscountPercentage = (originalPrice, currentPrice) =>
  Math.trunc(((originalPrice - currentPrice) / originalPrice) * 100) + '%';

export const products = [
  {
    _id: uuid(),
    title: 'Harry Potter And The Cursed Child',
    author: 'J K Rowling',
    img: HarryPotterAndTheCursedChild,
    price: 499,
    discountedPrice: 323,
    discountedAmount: calculateDiscountedAmount(499, 323),
    discountedPercentage: calculateDiscountPercentage(499, 323),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'Mans Search for Meaning',
    author: 'Viktor Frankl',
    img: MansSearchForMeaning,
    price: 399,
    discountedPrice: 300,
    discountedAmount: calculateDiscountedAmount(399, 300),
    discountedPercentage: calculateDiscountPercentage(399, 300),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'The Archer',
    author: 'Paulo Coelho',
    img: TheArcher,
    price: 299,
    discountedPrice: 259,
    discountedAmount: calculateDiscountedAmount(299, 259),
    discountedPercentage: calculateDiscountPercentage(299, 259),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'The Great Train Journey',
    author: 'Ruskin Bond',
    img: TheGreatTrainJourney,
    price: 100,
    discountedPrice: 95,
    discountedAmount: calculateDiscountedAmount(100, 95),
    discountedPercentage: calculateDiscountPercentage(100, 95),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    img: TheKiteRunner,
    price: 359,
    discountedPrice: 299,
    discountedAmount: calculateDiscountedAmount(359, 299),
    discountedPercentage: calculateDiscountPercentage(359, 299),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'Three Thousand Stitches',
    author: 'Sudha Murty',
    price: 199,
    img: ThreeThousandStitches,
    discountedPrice: 159,
    discountedAmount: calculateDiscountedAmount(199, 159),
    discountedPercentage: calculateDiscountPercentage(199, 159),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupery ',
    price: 150,
    img: TheLittlePrince,
    discountedPrice: 130,
    discountedAmount: calculateDiscountedAmount(150, 130),
    discountedPercentage: calculateDiscountPercentage(150, 130),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'Home Body',
    author: 'Rupi Kaur',
    price: 699,
    img: HomeBody,
    discountedPrice: 599,
    discountedAmount: calculateDiscountedAmount(699, 599),
    discountedPercentage: calculateDiscountPercentage(699, 599),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'War And Peace',
    author: 'SLeo Tolstoy',
    price: 299,
    img: WarAndPeace,
    discountedPrice: 219,
    discountedAmount: calculateDiscountedAmount(299, 219),
    discountedPercentage: calculateDiscountPercentage(299, 219),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'Landour Bazaar',
    author: 'Ruskin Bond',
    price: 199,
    img: LandourBazaar,
    discountedPrice: 160,
    discountedAmount: calculateDiscountedAmount(199, 160),
    discountedPercentage: calculateDiscountPercentage(199, 160),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'Love Sonnets Of Ghalib',
    author: 'Ghalib',
    price: 450,
    img: LoveSonnetsOfGhalib,
    discountedPrice: 399,
    discountedAmount: calculateDiscountedAmount(450, 399),
    discountedPercentage: calculateDiscountPercentage(450, 399),
    categoryName: 'fiction',
  },
  {
    _id: uuid(),
    title: 'Siddhartha',
    author: 'Hermmann Hesse',
    price: 379,
    img: Siddhartha,
    discountedPrice: 301,
    discountedAmount: calculateDiscountedAmount(379, 301),
    discountedPercentage: calculateDiscountPercentage(379, 301),
    categoryName: 'fiction',
  },

  //NON-FICTION
  {
    _id: uuid(),
    title: 'My Journey',
    author: 'A.P.J Abdul Kalam',
    img: MyJourney,
    price: 295,
    discountedPrice: 219,
    discountedAmount: calculateDiscountedAmount(295, 219),
    discountedPercentage: calculateDiscountPercentage(295, 219),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: 'ShoeDog',
    author: 'Knight Phil',
    img: ShoeDog,
    price: 399,
    discountedPrice: 356,
    discountedAmount: calculateDiscountedAmount(399, 356),
    discountedPercentage: calculateDiscountPercentage(399, 356),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: 'Why I Am An Atheist',
    author: 'Bhagat Singh',
    img: WhyIAmAnAtheist,
    price: 189,
    discountedPrice: 180,
    discountedAmount: calculateDiscountedAmount(189, 180),
    discountedPercentage: calculateDiscountPercentage(189, 180),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: 'Rajneeti',
    author: 'Gautam Chintamani ',
    img: Rajneeti,
    price: 699,
    discountedPrice: 299,
    discountedAmount: calculateDiscountedAmount(699, 299),
    discountedPercentage: calculateDiscountPercentage(699, 299),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: 'The Dhoni Touch',
    author: 'Bharat Sundaresan',
    img: TheDhoniTouch,
    price: 389,
    discountedPrice: 120,
    discountedAmount: calculateDiscountedAmount(389, 120),
    discountedPercentage: calculateDiscountPercentage(389, 120),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: 'The Diary Of A Young Girl',
    author: 'Anne Frank ',
    img: DiaryOfAYoungGirl,
    price: 189,
    discountedPrice: 129,
    discountedAmount: calculateDiscountedAmount(189, 129),
    discountedPercentage: calculateDiscountPercentage(189, 129),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: 'The Diary Of A Young Girl',
    author: 'Anne Frank ',
    img: DiaryOfAYoungGirl,
    price: 299,
    discountedPrice: 159,
    discountedAmount: calculateDiscountedAmount(299, 159),
    discountedPercentage: calculateDiscountPercentage(299, 159),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: "India's Struggle For Independence",
    author: 'Bipan Chandra',
    img: IndiasStruggleForIndependence,
    price: 799,
    discountedPrice: 319,
    discountedAmount: calculateDiscountedAmount(799, 319),
    discountedPercentage: calculateDiscountPercentage(799, 319),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: 'Karma',
    author: 'Sadhguru',
    img: Karma,
    price: 299,
    discountedPrice: 199,
    discountedAmount: calculateDiscountedAmount(299, 199),
    discountedPercentage: calculateDiscountPercentage(299, 199),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: 'Seven Secrets Of Shiva',
    author: 'Devdutt Pattanaik',
    img: SevenSecretsOfShiva,
    price: 299,
    discountedPrice: 234,
    discountedAmount: calculateDiscountedAmount(299, 234),
    discountedPercentage: calculateDiscountPercentage(299, 234),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: "Rumi's Little Book Of Life",
    author: 'Devdutt Pattanaik',
    img: RumisLittleBookOfLife,
    price: 499,
    discountedPrice: 126,
    discountedAmount: calculateDiscountedAmount(499, 126),
    discountedPercentage: calculateDiscountPercentage(499, 126),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: 'My Gita',
    author: 'Devdutt Pattanaik',
    img: MyGita,
    price: 499,
    discountedPrice: 389,
    discountedAmount: calculateDiscountedAmount(499, 389),
    discountedPercentage: calculateDiscountPercentage(499, 389),
    categoryName: 'non-fiction',
  },
  {
    _id: uuid(),
    title: 'Death',
    author: 'Sadhguru',
    img: Death,
    price: 199,
    discountedPrice: 99,
    discountedAmount: calculateDiscountedAmount(199, 99),
    discountedPercentage: calculateDiscountPercentage(199, 99),
    categoryName: 'non-fiction',
  },

  //SELF-HELP
  {
    _id: uuid(),
    title: 'Ikigai',
    author: 'Hector Gracia',
    img: Ikigai,
    price: 189,
    discountedPrice: 139,
    discountedAmount: calculateDiscountedAmount(189, 139),
    discountedPercentage: calculateDiscountPercentage(189, 139),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: "Life's Amazing Secrets",
    author: 'Gaur Gopal Das',
    img: LifesAmazingSecrets,
    price: 169,
    discountedPrice: 119,
    discountedAmount: calculateDiscountedAmount(169, 119),
    discountedPercentage: calculateDiscountPercentage(169, 119),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: 'Star With Why',
    author: 'Simon Sinek',
    img: StarWithWhy,
    price: 299,
    discountedPrice: 218,
    discountedAmount: calculateDiscountedAmount(299, 218),
    discountedPercentage: calculateDiscountPercentage(299, 218),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: 'The Power Of Your Subconsious Mind',
    author: 'Murphy Joseph',
    img: ThePowerOfYourSubconsiousMind,
    price: 289,
    discountedPrice: 200,
    discountedAmount: calculateDiscountedAmount(289, 200),
    discountedPercentage: calculateDiscountPercentage(289, 200),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: 'The Psycology Of Money',
    author: 'Morgan Housel',
    img: ThePsycologyOfMoney,
    price: 699,
    discountedPrice: 600,
    discountedAmount: calculateDiscountedAmount(699, 600),
    discountedPercentage: calculateDiscountPercentage(699, 600),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: 'Think And Grow Rich',
    author: 'Napoleon Hil',
    img: ThinkAndGrowRich,
    price: 899,
    discountedPrice: 799,
    discountedAmount: calculateDiscountedAmount(899, 799),
    discountedPercentage: calculateDiscountPercentage(899, 799),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: 'Think Like A Monk',
    author: 'Jay Shetty',
    img: ThinkLikeAMonk,
    price: 459,
    discountedPrice: 323,
    discountedAmount: calculateDiscountedAmount(459, 323),
    discountedPercentage: calculateDiscountPercentage(459, 323),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: 'Beleive In Yourself',
    author: 'Joseph Murphy',
    img: BeleiveInYourself,
    price: 799,
    discountedPrice: 299,
    discountedAmount: calculateDiscountedAmount(799, 299),
    discountedPercentage: calculateDiscountPercentage(799, 299),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: 'Atomic Habits',
    author: 'James Clear',
    img: AtomicHabits,
    price: 499,
    discountedPrice: 393,
    discountedAmount: calculateDiscountedAmount(499, 393),
    discountedPercentage: calculateDiscountPercentage(499, 393),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: 'Mindset',
    author: 'Dr Carol Dweck ',
    img: Mindset,
    price: 199,
    discountedPrice: 129,
    discountedAmount: calculateDiscountedAmount(199, 129),
    discountedPercentage: calculateDiscountPercentage(199, 129),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: 'Life',
    author: 'Radhakrishnan Pillai',
    img: ChanakyaInDailyLife,
    price: 756,
    discountedPrice: 399,
    discountedAmount: calculateDiscountedAmount(756, 399),
    discountedPercentage: calculateDiscountPercentage(756, 399),
    categoryName: 'self-help',
  },
  {
    _id: uuid(),
    title: 'Attached',
    author: 'Amir Levine',
    img: Attached,
    price: 366,
    discountedPrice: 323,
    discountedAmount: calculateDiscountedAmount(366, 323),
    discountedPercentage: calculateDiscountPercentage(366, 323),
    categoryName: 'self-help',
  },
];
